### ISSUE TITLE
Can't install by automatic, must be Manual

### ISSUE THREAD

**Issue by Leroy-X** [amb/blender-texture-tools#1]
Install test in blender 2.77, install by automatic can't find the addon, and should be through the manual,.

BTW,  does this can put all file in a folder, I am meaning, when I install by the manual, not support all file in a folder, like "blender-texture-tools", all file must be in the addons directory, sorry for my poor English.

Very thanks for your addon, it's very great :+1:

**Comment by amb** [comment]
What do you mean by install by automatic? I'm not aware of such option. All my Blender addons have been installed either through a .zip file or directly by a .py file.

Did you try downloading https://raw.githubusercontent.com/amb/blender-texture-tools/master/seamless.py then clicking "Install from File..." at the bottom of Blender User Preferences > Add-ons? That is currently the preferred installation route. I tried it and it seems to work fine. If you have any problems with it please specify.

**Comment by Leroy-X** [comment]
Glad to see your reply, I am mean install through the User Preferences, I download the .zip through the github, when I install form the User Preferences, blender can't find the addons, So I must copy the addons into the addons directory,  not support all file in a sub-folder. just happened with the .zip version:P

some iamge to description:

![01](https://cloud.githubusercontent.com/assets/13515498/16800632/cba80dc0-4928-11e6-9831-c3cbf7720219.png)
![02](https://cloud.githubusercontent.com/assets/13515498/16800635/ce30bccc-4928-11e6-825b-b102cb3e3bcf.png)
![03](https://cloud.githubusercontent.com/assets/13515498/16800640/d0960dd2-4928-11e6-9203-0bd40c85527d.png)

Thanks:D

**Comment by amb** [comment]
Thanks for the detailed explanation. ZIP files are currently not supported. There is no official release as I don't think the addon is complete yet. How the installation currently goes is to save the file I linked in the previous post to your computer and then go to Blender settings and Install from File, select the .py file, not the .zip file. I will consider making a ZIP if the project reaches a point where it can be called complete or at least version 1.0.

**Comment by Leroy-X** [comment]
Thanks you care this, .zip is much more clear in the addons foloder when the addon have many files.
 :+1:

**Comment by amb** [comment]
I'm closing this as there are now separate releases that the working .zip can be downloaded from.
