### ISSUE TITLE
Error on non-square images

### ISSUE THREAD

**Issue by AlfioSaitta** [amb/blender-texture-tools#2]
Get a error when the plugin try to scale the image on:

Linux Arch kernel 5.3.7-arch1-1-ARCH
Gnome Desktop 3.34
Blender 2.82 (compiled from sources)

> Traceback (most recent call last):
>   File "/home/alfio/.config/blender/2.82/scripts/addons/blender-texture-tools/bpy_amb/master_ops.py", line 40, in invoke
>     return self.execute(context)
>   File "/home/alfio/.config/blender/2.82/scripts/addons/blender-texture-tools/image_ops.py", line 70, in execute
>     sourcepixels = self.payload(sourcepixels, context)
>   File "/home/alfio/.config/blender/2.82/scripts/addons/blender-texture-tools/__init__.py", line 898, in gimpify
>     imask[0 : sys + 1, sxs : xs - 1] = numpy.fliplr(imask[0 : sys + 1, 0 : sxs - 1])
> ValueError: could not broadcast input array from shape (151,199) into shape (151,100)
> 
> location: <unknown location>:-1

**Comment by amb** [comment]
Which version of the addon are you using? I remember already fixing that bug. Have you tried the latest from master?

**Comment by AlfioSaitta** [comment]
No, the released version (v1.0-b2.80)

Now i try the master.

**Comment by AlfioSaitta** [comment]
Same issue with the version 0.1.17

![immagine](https://user-images.githubusercontent.com/10280718/67677137-8e016980-f983-11e9-89c4-dd1586d97675.png)

> Traceback (most recent call last):
>   File "/home/alfio/.config/blender/2.82/scripts/addons/blender-texture-tools/bpy_amb/master_ops.py", line 40, in invoke
>     return self.execute(context)
>   File "/home/alfio/.config/blender/2.82/scripts/addons/blender-texture-tools/image_ops.py", line 70, in execute
>     class ImageOperatorGenerator(master_ops.OperatorGenerator):
>   File "/home/alfio/.config/blender/2.82/scripts/addons/blender-texture-tools/__init__.py", line 899, in gimpify
> ValueError: could not broadcast input array from shape (350,220) into shape (350,350)
> 
> location: <unknown location>:-1

**Comment by AlfioSaitta** [comment]
Ok... im sorry... all work with sharme after the blender restart
