### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by crazyrobinhood** [amb/blender-texture-tools#3]
Just a proposal for expanding the readme with some kind of help.
(since I was unable to install addon from zip and I don't know if every .py should be launched trough internal editor or not)
Thanks in advance for your work and time.

**Comment by amb** [comment]
Sure, it's just not a priority. Plus you should be able to download the release .zip and install it directly from Blender.

**Comment by crazyrobinhood** [comment]
Unfortunately it won't appear in side panel nor in plugin list if I try to install from zip file. maybe is it a OS issue? I'm testing it on Linux PopOs! (Debian). I noticed that the files are straight in the folder of addons under scripts of the version number ( in my case 2.81) without being grouped inside a own folder.

**Comment by amb** [comment]
I made a new release that includes the folder inside the .zip. I tested it with Ubuntu 18.04 and it seems to work from directly installing the .zip from inside Blender. Try it out to see if it works for you.

**Comment by crazyrobinhood** [comment]
Great work! now everything is fine.
Some errors in a few functions: fractalize:

> 18 function calls in 0.009 seconds
> 
>    Ordered by: cumulative time
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.001    0.001    0.009    0.009 __init__.py:696(_pl)
>         2    0.008    0.004    0.008    0.004 {method 'copy' of 'numpy.ndarray' objects}
>         3    0.000    0.000    0.000    0.000 bpy_types.py:707(__getattribute__)
>         3    0.000    0.000    0.000    0.000 {method 'path_resolve' of 'bpy_struct' objects}
>         1    0.000    0.000    0.000    0.000 utils.py:94(__exit__)
>         5    0.000    0.000    0.000    0.000 {built-in method builtins.getattr}
>         1    0.000    0.000    0.000    0.000 utils.py:75(profiling_end)
>         1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
>         1    0.000    0.000    0.000    0.000 utils.py:91(__enter__)
> 
> 
> 
> Traceback (most recent call last):
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/bpy_amb/master_ops.py", line 43, in invoke
>     return self.execute(context)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/image_ops.py", line 64, in execute
>     sourcepixels = self.payload(sourcepixels, context)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/__init__.py", line 712, in _pl
>     pix[:ihh, :iwh, :] *= smol
> ValueError: operands could not be broadcast together with shapes (500,836,4) (500,837,4) (500,836,4) 
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

Gimp seamless:

> 44 function calls (40 primitive calls) in 2.015 seconds
> 
>    Ordered by: cumulative time
>    List reduced from 32 to 10 due to restriction <10>
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000    2.015    2.015 __init__.py:875(<lambda>)
>         1    2.008    2.008    2.015    2.015 __init__.py:592(gimpify)
>       5/3    0.000    0.000    0.007    0.002 {built-in method numpy.core._multiarray_umath.implement_array_function}
>       2/1    0.000    0.000    0.003    0.003 <__array_function__ internals>:2(roll)
>       2/1    0.003    0.002    0.003    0.003 numeric.py:1106(roll)
>         1    0.000    0.000    0.003    0.003 <__array_function__ internals>:2(copy)
>         4    0.003    0.001    0.003    0.001 {built-in method numpy.array}
>         1    0.000    0.000    0.003    0.003 function_base.py:745(copy)
>         1    0.000    0.000    0.000    0.000 {built-in method numpy.zeros}
>         1    0.000    0.000    0.000    0.000 bpy_types.py:707(__getattribute__)
> 
> 
> 
> Traceback (most recent call last):
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/bpy_amb/master_ops.py", line 43, in invoke
>     return self.execute(context)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/image_ops.py", line 64, in execute
>     sourcepixels = self.payload(sourcepixels, context)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/__init__.py", line 875, in <lambda>
>     self.payload = lambda self, image, context: gimpify(image)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/__init__.py", line 614, in gimpify
>     imask[0 : sys + 1, sxs:xs] = numpy.fliplr(imask[0 : sys + 1, 0:sxs])
> ValueError: could not broadcast input array from shape (501,836) into shape (501,837)
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

histogram seamless:

> 259 function calls (240 primitive calls) in 2.426 seconds
> 
>    Ordered by: cumulative time
>    List reduced from 78 to 10 due to restriction <10>
> 
>    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
>         1    0.000    0.000    2.426    2.426 __init__.py:884(_pl)
>         1    2.009    2.009    2.027    2.027 __init__.py:592(gimpify)
>         1    0.021    0.021    0.400    0.400 __init__.py:211(gaussianize)
>     31/14    0.000    0.000    0.365    0.026 {built-in method numpy.core._multiarray_umath.implement_array_function}
>         3    0.000    0.000    0.348    0.116 <__array_function__ internals>:2(unique)
>         3    0.000    0.000    0.347    0.116 arraysetops.py:151(unique)
>         3    0.061    0.020    0.347    0.116 arraysetops.py:297(_unique1d)
>         3    0.265    0.088    0.265    0.088 {method 'argsort' of 'numpy.ndarray' objects}
>        10    0.000    0.000    0.018    0.002 fromnumeric.py:55(_wrapfunc)
>         1    0.000    0.000    0.018    0.018 __init__.py:39(gauss_curve)
> 
> 
> 
> Traceback (most recent call last):
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/bpy_amb/master_ops.py", line 43, in invoke
>     return self.execute(context)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/image_ops.py", line 64, in execute
>     sourcepixels = self.payload(sourcepixels, context)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/__init__.py", line 886, in _pl
>     blended = gimpify(gimg)
>   File "/home/nk/.config/blender/2.81/scripts/addons/blender-texture-tools/__init__.py", line 614, in gimpify
>     imask[0 : sys + 1, sxs:xs] = numpy.fliplr(imask[0 : sys + 1, 0:sxs])
> ValueError: could not broadcast input array from shape (501,836) into shape (501,837)
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

Hope it helps!
Great work by the way!

**Comment by amb** [comment]
Yeah most of the functions are tested and run on powers of two textures like 512x512, 1024x1024 etc. So some issues may happen with dimensions that aren't those.

**Comment by amb** [comment]
Closing this as the .zip issue is fixed.
